# Generated by Django 4.0.1 on 2022-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_model', models.CharField(max_length=100)),
                ('mob_ram', models.CharField(max_length=10)),
                ('mob_rom', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
