# Generated by Django 4.0.1 on 2022-01-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobilesDetails',
            new_name='MobilesDetail',
        ),
    ]
